baseURL = 'https://clemovitch.com/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
title = 'Clément Viktorovitch'
copyright = 'Tous droits réservés.'
enableRobotsTXT = true
disableKinds = ['RSS', 'sitemap', '404', 'section', 'taxonomy', 'term']