name: Continuous Deployment
on:
    push:
        branches: [main]

jobs:
    deploy_job:
        runs-on: ubuntu-latest
        name: deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '14'

            - name: Install Dependencies
              run: npm install --development

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.124.0'
                  extended: true

            - name: Build
              run: npm run build

            - name: Deploy
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  password: ${{ secrets.DEPLOY_PASSWORD }}
                  server: ${{ secrets.DEPLOY_SERVER }}
                  local_path: './public/*'
                  remote_path: ${{ secrets.DEPLOY_PATH }}
                  delete_remote_files: true
